version: '3'
services:
  security:
    image: security
    restart: on-failure:5
    depends_on:
      - redis
      - passwordDB
      - userdb
    ports:
      - 8082:8081
    environment:
      JWT_SECRET: secret
  redis:
    image: redis
  passwordDB:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: mysecretpassword
    volumes:
      - dbdata:/var/lib/postgresql/data
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  userdb:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - userdb:/data/db
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8083:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@userdb:27017/
  
volumes:
  dbdata:
  userdb: